# Generated by Django 3.0.5 on 2020-04-12 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200407_2308'),
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday_day',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday_month',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Месяц рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Год рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='fav_category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fav_category1', to='category.Category', verbose_name='Категория1'),
        ),
        migrations.AddField(
            model_name='user',
            name='fav_category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fav_category2', to='category.Category', verbose_name='Категория2'),
        ),
        migrations.AddField(
            model_name='user',
            name='fav_category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fav_category3', to='category.Category', verbose_name='Категория3'),
        ),
        migrations.AddField(
            model_name='user',
            name='fav_category4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fav_category4', to='category.Category', verbose_name='Категория4'),
        ),
    ]
