# Generated by Django 3.0.5 on 2020-04-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_user_is_social_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='Mr.Anonim', max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
