# Generated by Django 3.0.5 on 2020-04-26 11:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название дня недели')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название дня недели')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название дня недели')),
                ('name_az', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название дня недели')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название месяца')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название месяца')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название месяца')),
                ('name_az', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название месяца')),
            ],
        ),
        migrations.CreateModel(
            name='SeoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='h1 главной')),
                ('index_h1_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='h1 главной')),
                ('index_h1_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='h1 главной')),
                ('index_h1_az', models.CharField(blank=True, max_length=255, null=True, verbose_name='h1 главной')),
                ('index_description', models.TextField(blank=True, null=True, verbose_name='description главной')),
                ('index_description_en', models.TextField(blank=True, null=True, verbose_name='description главной')),
                ('index_description_ru', models.TextField(blank=True, null=True, verbose_name='description главной')),
                ('index_description_az', models.TextField(blank=True, null=True, verbose_name='description главной')),
                ('index_keywords', models.TextField(blank=True, null=True, verbose_name='keywords главной')),
                ('index_keywords_en', models.TextField(blank=True, null=True, verbose_name='keywords главной')),
                ('index_keywords_ru', models.TextField(blank=True, null=True, verbose_name='keywords главной')),
                ('index_keywords_az', models.TextField(blank=True, null=True, verbose_name='keywords главной')),
                ('index_seo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст главной')),
                ('index_seo_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст главной')),
                ('index_seo_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст главной')),
                ('index_seo_az', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст главной')),
            ],
        ),
    ]
