# Generated by Django 3.0.5 on 2020-04-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotag',
            name='index_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title главной'),
        ),
        migrations.AddField(
            model_name='seotag',
            name='index_title_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title главной'),
        ),
        migrations.AddField(
            model_name='seotag',
            name='index_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title главной'),
        ),
        migrations.AddField(
            model_name='seotag',
            name='index_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title главной'),
        ),
    ]
