# Generated by Django 3.0.5 on 2020-04-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200426_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
