# Generated by Django 3.0.5 on 2020-04-26 08:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20200423_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_description_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_h1_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название категории)'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_h1_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название категории)'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_h1_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название категории)'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_title_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_text_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_description_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_h1_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название подкатегории)'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_h1_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название подкатегории)'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_h1_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название подкатегории)'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_title_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='seo_text_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='seo_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='seo_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу'),
        ),
    ]
