# Generated by Django 3.0.5 on 2020-04-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20200426_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='page_keywords_az',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_keywords_az',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
    ]
