# Generated by Django 2.2.7 on 2020-04-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20200426_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Изображение в шапку'),
        ),
    ]
