# Generated by Django 3.0.5 on 2020-04-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_category_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_podcast',
            field=models.BooleanField(default=False, verbose_name='Подкасты?'),
        ),
    ]
