# Generated by Django 3.0.5 on 2020-04-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20200407_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'Реакция на комментарий', 'verbose_name_plural': 'Реакция на комментарий'},
        ),
    ]
