# Generated by Django 2.2.7 on 2020-04-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20200412_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(null=True, upload_to='video_thumb/', verbose_name='Изображение (550 x 300)'),
        ),
    ]
