# Generated by Django 2.2.7 on 2020-04-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20200413_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Дизлайков'),
        ),
    ]
