# Generated by Django 3.0.5 on 2020-04-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_dislikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentvideo',
            old_name='videos',
            new_name='video',
        ),
    ]
