# Generated by Django 2.2.7 on 2020-04-14 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0006_auto_20200413_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(blank=True, null=True, verbose_name='Лайк?')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Реакция на видео',
                'verbose_name_plural': 'Реакция на видео',
            },
        ),
    ]
