# Generated by Django 2.2.7 on 2020-04-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_videolike'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolike',
            name='is_dislike',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='ДизЛайк?'),
        ),
        migrations.AlterField(
            model_name='videolike',
            name='is_like',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Лайк?'),
        ),
    ]
