# Generated by Django 3.0.5 on 2020-04-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20200414_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='disliked_by_users',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='liked_by_users',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
