# Generated by Django 3.0.5 on 2020-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20200415_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentvideo',
            name='disliked_by_users',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='commentvideo',
            name='liked_by_users',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
