# Generated by Django 3.0.5 on 2020-04-15 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0011_auto_20200415_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videolike',
            options={'verbose_name': 'Реакция на видео (Лайк)', 'verbose_name_plural': 'Реакция на видео (Лайк)'},
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='is_dislike',
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='is_like',
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='user',
        ),
        migrations.AddField(
            model_name='videolike',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='VideoDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Реакция на видео (ДизЛайк)',
                'verbose_name_plural': 'Реакция на видео (ДизЛайк)',
            },
        ),
    ]
