# Generated by Django 3.0.5 on 2020-04-15 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0013_auto_20200415_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ManyToManyField(blank=True, to='video.Video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'История видео',
                'verbose_name_plural': 'История видео',
            },
        ),
    ]
