# Generated by Django 2.2.7 on 2020-04-23 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_videohistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Проверено?'),
        ),
        migrations.AlterField(
            model_name='video',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.SubCategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
    ]
