# Generated by Django 3.0.5 on 2020-05-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0015_auto_20200423_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видое'),
        ),
    ]
